import { ThemeProvider } from '@emotion/react';
import type { AppProps } from 'next/app';
import Head from 'next/head';
import '../styles/globals.scss';

import { enableStaticRendering } from "mobx-react-lite";
import { LanguageStoreProvider } from '@/data/withMobx/Language/LanguageStoreProvider';
// there is no window object on the server
enableStaticRendering(typeof window === "undefined");

export default function App({ Component, pageProps }: AppProps) {
  return <LanguageStoreProvider {...pageProps}>
    <Head>
      <title>Web Calculator</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Component {...pageProps} />
  </LanguageStoreProvider>
}
